export const LOGIN_START = 'LOGIN_START';
export const GET_INFO_START = 'GET_INFO_START';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'GET_INFO_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CLEAR_ADMIN_SESSION = 'CLEAN_ADMIN_SESSION';
